% Generated by extoltoprolog
:-(set_prolog_flag(singleton_warning,off)).
:-(discontiguous(/(test,1))).
:-(initialization(;(main,','(write('error: unexpected failure in main'),','(nl,halt(1)))))).
:-(builtin_load_builtins(module(A,B,C)),','(','(member(-(/(/(write,1),pred),prolog(/(write,1))),B),!),','(','(member(-(/(/(is,2),pred),prolog(/(is,2))),B),!),','(','(member(-(/(/(halt,0),pred),prolog(/(halt,0))),B),!),','(','(member(-(/(/(member,2),pred),prolog(/(member,2))),B),!),','(','(member(-(/(/(+,3),pred),prolog(/(+,3))),B),!),','(','(member(-(/(/(-,3),pred),prolog(/(-,3))),B),!),','(','(member(-(/(/(fib,2),pred),prolog(/(fib,2))),B),!),','(member(-(/(/(main,0),pred),prolog(/(main,0))),B),!))))))))).
:-(+(A,B,C),is(C,+(A,B))).
:-(-(A,B,C),is(C,-(A,B))).
:-(fib(0,1),true).
:-(fib(1,1),true).
:-(fib(A,B),','(-(A,1,C),','(fib(C,D),','(-(A,2,E),','(fib(E,F),+(D,F,B)))))).
:-(main,','(','(fib(12,A),write(A)),halt)).
